apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: check-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "docker.io/gkovan/*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfeA3l3o61HpdOpJx7e/+mfzRCo+s
          64XhSCM5pSedzxWHYG4NsMlrr9X65il8WjHO99rw7ADw6o4AQl8+fKkSHg==
          -----END PUBLIC KEY-----
